baseURL: https://vivecodigo.org/
languageCode: es-mx
defaultContentLanguage: es
title: ViveCodigo.org
theme: hugo-theme-stack
copyright: MakingDevs

pagination:
  pagerSize: 10

services:
  disqus:
    shortname: vivecodigo

permalinks:
  blog: blog/:year/:month/:day/:title/
  page: /:slug/

taxonomies:
  tag: tags
  category: categories

params:
  mainSections:
    - blog
  featuredImageField: image
  rssFullContent: true
  favicon: favicon.png
  description: "El podcast para desarrolladores de software."

  footer:
    since: 2011
    customText: "El podcast para desarrolladores de software."

  dateFormat:
    published: "Jan 02, 2006"
    lastUpdated: "Jan 02, 2006 15:04 MST"

  sidebar:
    compact: false
    emoji: ">"
    subtitle: "El podcast para desarrolladores de software."
    avatar:
      enabled: true
      local: true
      src: images/avatar.jpg

  article:
    headingAnchor: false
    math: false
    toc: true
    readingTime: true
    license:
      enabled: false

  comments:
    enabled: true
    provider: disqus

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 20
    page:
      - type: toc

  opengraph:
    twitter:
      site: ViveCodigo
      card: summary_large_image

  defaultImage:
    opengraph:
      enabled: true
      local: false
      src: images/bg_wall.png

  colorScheme:
    toggle: true
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main:
    - identifier: home
      name: Inicio
      url: /
      weight: -100
      params:
        icon: home
    - identifier: blog
      name: Blog
      url: /blog/
      weight: -90
      params:
        icon: archives

  social:
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/ViveCodigo
      params:
        icon: brand-twitter
    - identifier: vimeo
      name: Vimeo
      url: https://vimeo.com/makingdevs
      params:
        icon: link
    - identifier: itunes
      name: iTunes
      url: https://itunes.apple.com/mz/podcast/vivecodigo.org-podcast/id722889939
      params:
        icon: link

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 200

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: true
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
